pipelines:
  test-run:
    group: sample
    environment_variables:
      GIT_USERNAME: "{{SECRET:[vault][GIT_USERNAME]}}"
    materials:
      acceptancetesting:
        git: https://github.com/NikoHeikki/getting-started-repository.git
        branch: main
    stages:
      - run-command:
          jobs:
            run:
              elastic_profile_id: demo-app
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - "-c"
                    - "echo $GIT_USERNAME"
